#video 45
#command run (docker-compose up--build)
version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    # command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000 
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: django-server
    depends_on:
      - redis
      - db


  redis:
    image : redis:7.4.2-alpine
    container_name: redis-server

#video 45
  db:
    image: postgres:15
    container_name: postgres-server
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=amazon
    ports:
      - "5432:5432" 

  celery:
    image: celery:4.0.2
    container_name: celery-server
    build: .
    volumes:
      - .:/app
    command: celery -A project worker -l INFO
    depends_on:
      - backend


volumes:
  postgres_data:
