#video 45
#command run (docker-compose up--build)
version: '3.8'

services:
  backend:
    build: .
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: django-server
    depends_on:
      - redis


  redis:
    image : redis:7.4.2-alpine
    container_name: redis-server