"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&(rd--nj8j9rc$48gmr0!5@^(3qrbhl1^%qy(8i&s^*#76r4o+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'accounts', # video 42  # top

    'django.contrib.admin', # after top
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites', # error with docker createsuperuser video 45
    'allauth', # full auth system video 43
    'allauth.account', # full auth system video 43
    'allauth.socialaccount', # full auth system video 43
    'dj_rest_auth.registration', # full auth system video 43

    'taggit',
    'rest_framework',
    'django_filters',
    'drf_yasg',  
    "debug_toolbar",
    "django_bootstrap5",  # video 42
    'rest_framework.authtoken', # video 42
    'rest_framework_simplejwt',  # video 43
    'dj_rest_auth', # full auth system video 43


    'products',
    'settings',
    'orders',
]

SITE_ID = 1 # fix error to pass to admin dashborad panel


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # # full auth system video 43
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "debug_toolbar.middleware.DebugToolbarMiddleware",

]

INTERNAL_IPS = [
    # ...
    "127.0.0.1", # debug tool bar
    # ...
]

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # التحكم في من يستطيع رؤية الـ Toolbar
}


ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'settings.settings_context_processor.get_settings',
                'orders.cart_context_processor.get_cart_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.TokenAuthentication', # normal AUTH
        'rest_framework_simplejwt.authentication.JWTAuthentication', #JWT VIDEO 43
    ]
}

# full auth system video 43 
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#video 45
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "amazon",
        "USER": "postgres",
        "PASSWORD": "123",
        "HOST": "db",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = 'media/'
MEDIA_ROOT  = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 
#         'TIMEOUT': 60,
#     }
# }

#docker redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache', 
        'LOCATION': 'redis://redis:6378/0',
        'TIMEOUT': 60,
    }
}

# # celery video 46
# Celery settings
# Configure Celery Broker (MEMORY DB broker)  (Redis):

# # # setting with out docker
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_BACKEND_RESULT = 'redis://localhost:6379/0'

# command run celeery  video 46
#celery -A your_project worker --loglevel=info
#celery -A project worker -l info

#setting with docker video 46
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_BACKEND_RESULT = 'redis://redis:6379/0'


AUTHENTICATION_BACKENDS = [ # video 41 # use to log in with email or username
    'accounts.backend.EmailOrUsernameLogin',    # app name . file name . class name
    'django.contrib.auth.backends.ModelBackend', 
]


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # live # video 41
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # test from consol # video 41


#EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" # video 41
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp-relay.gmail.com"
EMAIL_HOST_PASSWORD = "zssdmbodbjxebbov"
EMAIL_HOST_USER = "ahmed007eg@gmail.com"
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/' # video 42
